[package]
name = "entrance"
version = "0.1.0"
authors = ["Varvara Bondarenko <varvara.bondarenko14@gmail.com>", "Renato Diaz <diazrenato2001@outlook.com>"]
description = "vault 76 codebase"
repository = "https://github.com/NrgNinja/vault-76"
readme = "README.md"
edition = "2021"

[dependencies]
blake3 = "1.5.1"
clap = "3.1.6"

[profile.release]
debug = false

[profile.dev.package."*"] # +
codegen-units = 1 # better optimizations
opt-level = 's'
